[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.2.1",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
]
